# Generated by Django 5.1.5 on 2025-01-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=500)),
                ('post_img', models.ImageField(blank=True, null=True, upload_to='post_img/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
